//BOA PRATICA DE PROGRAMAÇÃO - VAMOS EXPORTAR TODOS TIPOS DE AÇÕES VAMOS EXPORTAR DAQUI DE DENTRO

//export const BOTAO_CLICADO = 'BOTAO_CLICADO';


//para usar, devemos importar

//ALTERAMOS O EVENTO ACIMA, POIS VAMOS UTILIZAR O REDUX SAGA PARA PROMISSES/FUNÇÃO ASINCRONA


export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';
